# Header
menu:
  Home: /
  Archives: /archives
  Projects: /projects
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-28958629-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
